services:
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./mysql/my_data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
    tty: true
    restart: always
    ports:
      - 13306:3306